### ISSUE TITLE
Versions widget enhancement

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#10]
- [ ] ~~highlight version by color depending on whether it was created by machine or human~~
- [x] re-order some columns
- [ ] ~~maybe also the possibility to detach the widget (as in jobs widget) to make use of whole horizontal space~~

**Comment by DRRV** [comment]
It is strange to have the "versions" button in the "main" widget (document, jobs, version,user activity).
It should also appear  in the overview/document manager... or accessible with right-click on the page image.
