### ISSUE TITLE
Change focus of lines/baselines according to text alignment

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#101]
@EvaMLang 
When a line or baseline is focused / zoomed into, it is currently centered in x-direction in the canvas. Change this to left justification (or better: depending on the text alignment in the transcription area!)

**Comment by EvaMLang** [comment]
see also issue #60

**Comment by jkloe** [comment]
Probably not needed, as you can change the alignment of the text to be centered which will lead to the desired effect that text and image are underneath each other

**Comment by EvaMLang** [comment]
The left-alignment is something our transcriber has asked for for several months now as it really speeds up transcription when the eyes can remain focused on the same spot of the monitor...

It would indeed be great to have some option to allow for left/center/right alignment of the current text box (table cell / text region) defaulting to whatever.
