### ISSUE TITLE
Document Manager: update to current collection missing

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#105]
1. Open Document Manager for current collection A
2. Switch to new collection B
3. Go to open Document Manager 
4. double-click on any page

After carrying out all four steps, the canvas now displays the selected page from the old document A (step 1). 

Expectation: Automatic update of selected document in the Document Manager to present pages (and info) of document B after it was selected in the main window / list of documents .

**Comment by hackmanschorsch** [comment]
changed so that opening a collection includes also loading of it's first document
