### ISSUE TITLE
TextRecognitionConfigDialog: "Share model" does not always work for admin 

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#111]
The dialog checks if the currently selected collection (storage.collId) is the same as the one the model shall be shared to. This check is not relevant if admin is logged in, as he sees all models in each collection.

Fix: in the server, select all collections a model is assigned to and send it to the GUI. Then do a check on acutal assignments.

**Comment by hackmanschorsch** [comment]
fixed with isAdmin check
