### ISSUE TITLE
CrowdSourcing - dialog issues

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#129]
- [x] date chooses is off by one month (selecting August 8 reveils 2017-07-08!!!)
- [x] dialog offers setup for CS project but selection is not remembered or saved onces the tick-box for "crowdsourcing" is ticked, neither the OK nor the Cancel button can be used to close the dialog window

**Comment by hackmanschorsch** [comment]
both bugs  will be fixed in the next Snapshot

**Comment by kahlep** [comment]
I will release a new snapshot version tomorrow!

**Comment by kahlep** [comment]
I just released 1.3.5.1-SNAPSHOT of TranskribusSwtGui which includes commit 1b48240e6b6e51890782b54b254fe9a83fdc8e42
