### ISSUE TITLE
Table Editor: Create BorderLines

### ISSUE THREAD

**Issue by flow79** [Transkribus/TranskribusSwtGui#140]
Buttons, e.g. top border should toggle the status of the line, but leave others unaffected. Currently, e.g.  it is not possible to create a cell which has all border lines visible except the bottom line

**Comment by EvaMLang** [comment]
Suggestion from user end would be a submenu allowing more than one selection at the same time. 
E.g.: Ctrl-key plus selecting top, left, right border menu entries. Will investigate...

**Comment by jkloe** [comment]
@EvaMLang either that or just hitting a button (ctrl?) while adding the borders will leave other borders unaffected as @flow79 suggested. I don't think that menu's with checkboxes exist in SWT, you would have to create ToolBox, as with the visibility settings (eye toolbar btn!)
