### ISSUE TITLE
Parent-ID set to -1 after LA analysis

### ISSUE THREAD

**Issue by jlmeunier** [Transkribus/TranskribusSwtGui#143]
After Line Detection by NCSR_tS_LA 1.1, the Parent-ID of the page version is -1.
Also the Status is "IN_PROGRESS" (but the jobs has properly finished).

![image](https://user-images.githubusercontent.com/15045456/29555167-09fca04e-8722-11e7-96c6-97831effb49b.png)

**Comment by kahlep** [comment]
The status of this transcript version refers to the transcription task. After running a job on an empty page, it automatically transitions from "NEW" to "IN_PROGRESS".
The parent ID was indeed not set in set in the layout analysis job, which is fixed now and will be included in the next deployment of the LA module.
