### ISSUE TITLE
Document Metadata: add Text field to get/set external ID

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#144]
Currently one String is foreseen in the TrpDocMetadata bean to handle external IDs. This can be immediately added to the DocMd widget.

To be clarified:
Do we have to alter the underlying datastructure (Oracle VARCHAR2 255 characters) in order to handle hierarchical structure of IDs?

**Comment by hackmanschorsch** [comment]
added hierarchy, backlink and authority as doc metadata as well
