### ISSUE TITLE
Collection Overview Table - add last edited (editor, date/time)

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#148]
It would be great to have an additional column in the collection overview table (Server -> Collections -> Table showing documents in the collection) indicating
- [x] name / email of last person who changed a page in the document
- [x] time of last save action (i.e. last change)

I believe that these statistics are already available via REST services.

**Comment by hackmanschorsch** [comment]
functionality can be found in Document Manager
