### ISSUE TITLE
Status settings changes to in progress

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#149]
Manual actions (simple save, setting of Text Regions followed by save action) does not change status from new to in_progress. Status changes appear only after (external) tools are called.

![grafik](https://user-images.githubusercontent.com/17451573/30366564-bb654d22-986b-11e7-9e35-c7505b944cd0.png)

**Comment by hackmanschorsch** [comment]
A save from status 'NEW' changes status automatically into 'InProgress' (until next release)
