### ISSUE TITLE
Export specific version 

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#153]
Version status is only considered for the first page when exporting a specific version of (several or all) pages within a document.

For example, if I export the Ground Truth version of a document, I receive the correct GT version for the first page and the latest (which is IN PROGESS) for every other page.

**Comment by hackmanschorsch** [comment]
@EvaMLang one further enquiry: If you want to export e.g. your GT files and only 10 out of 100 pages in your documents are GT then you want only these pages exported, right?

**Comment by EvaMLang** [comment]
@hackmanschorsch Yes, this would be my understanding. The export should only contain the (sub)set of pages which match the status. If a status cannot be applied to a page in the document, skip it.

**Comment by hackmanschorsch** [comment]
Will be available in the next Snapshot release.
