### ISSUE TITLE
Use exif orientation tag

### ISSUE THREAD

**Issue by hollaus** [Transkribus/TranskribusSwtGui#154]
Currently the image orientation stored in exif is ignored.

**Comment by kahlep** [comment]
This should be dealt with in `org.eclipse.swt.graphics.Image`, which does not respect that information (https://bugs.eclipse.org/bugs/show_bug.cgi?id=499908).

Please attach a sample image so I can try to implement a workaround for images from DocScan.

**Comment by hollaus** [comment]
![screenshot_nomacs](https://user-images.githubusercontent.com/8059808/31759490-ded97690-b4b1-11e7-85fd-2336e331d7b4.jpg)
screenshot of the image in nomacs, which uses the exif orientation tag.

![screenshot](https://user-images.githubusercontent.com/8059808/31759386-8345a47a-b4b1-11e7-8b54-a1e8dbaf1008.jpg)
screenshot of the image in transkribus

![img_20171019_093236](https://user-images.githubusercontent.com/8059808/31759374-782c21e0-b4b1-11e7-8163-39c5e41dbdb1.jpg)
original image

**Comment by kahlep** [comment]
This issue does still exist for respective document images.
Depends on:
1. Fix for https://github.com/Transkribus/TranskribusInterfaces/issues/5
2. Test all tools not using ImageUtils for image loading to obey the orientation tag
3. Then revert change done in: https://github.com/Transkribus/TranskribusSwtGui/issues/208

**Comment by kahlep** [comment]
- fix also in eu.transkribus.core.util.ImgUtils (e.g. readImageDimensions()) 

- binarized images on filestore do not include the orientation anymore and are then useless
