### ISSUE TITLE
Merging lines mixes up word order

### ISSUE THREAD

**Issue by dariok** [Transkribus/TranskribusSwtGui#157]
If you merge, say, 4 lines:

    26
    19 ½ — —
    22 1/3 — —
    16 1/5 — —

the result may become completely mixed up; in my instance, the resulting line read:

    22 1/3 — —19 ½ — —2616 1/5 — —

This happens whether you merge all lines at once or one by one from left to right.

---

Edit: This concerns version 1.3.4; couldn't test yet whether this is still around in 1.3.5 

---

Edit 2: This is still true in v. 1.3.5 at least when merging more than 2 lines; note, though, that this does seem to happen randomly, i.e., sometimes the order is correct

**Comment by hackmanschorsch** [comment]
Should be solved with issue #203 
Previously the merged lines were sorted with their coordinates - now with their reading order
