### ISSUE TITLE
Training of models: copy test document to source collection

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TranskribusSwtGui#159]
If a user starts an HTR training, the test document (maybe also the training document) should be added to the source collection (where the training started)

**Comment by hackmanschorsch** [comment]
Deployed and tested on test server. Productive version will follow. Currently only the test pages will be copied because of the additional time and storage needed.

**Comment by hackmanschorsch** [comment]
duplicate #142

**Comment by hackmanschorsch** [comment]
now on productive server
