### ISSUE TITLE
HTR dialog redesign

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#17]
- how to select/search models?
- do not display document metadata (only a button to display dialog)

**Comment by kahlep** [comment]
* Improve selection of pages in HTR Training Dialog, e.g. by using a TreeViewer?
* Add a table for language models in HTR Config Dialog

**Comment by kahlep** [comment]
Done:
* HtrTrainingDialog
  * redesigned with TreeViewer
* TextRecognitionConfigDialog
  * show final values from training evaluation
  * show nr of lines/words trained
  * language in HTR table
  * show parameters of training

Open issue:
* TextRecognitionDialog
  * show CER evaluation results per page of test/train set
