### ISSUE TITLE
Comparing quality of transcriptions on document level

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#173]
Currently, the user can manually compare two different versions on page level only. Functionality should allow comparison on document level similar to the "Run HTR" options. 

- By default, the newest GT version should be considered as basis. 
- The hypothesis should allow selection via search string, also an option to take the most current version and possibly offer the user a list of HTR models which were already run on the (full) document.

**Comment by hackmanschorsch** [comment]
Frist version of compare tool (starting from 1.4.3) takes first GT version as basis and first 'In Progress' as hypothesis automatically.
Further versions of the compare tool will then allow to choose other hypothesis as well.
@EvaMLang: Can you please explain the 'selection via search string'.

**Comment by EvaMLang** [comment]
Re:searchstring @hackmanschorsch When working on document level, it would be nice to identify 
- the newest version created between YYYY-MM-DD and yyyy-mm-dd across the document 
- the newest version created by authors A or B
- the newest version of status IN_PROGRESS | FINAL | DONE | GT | ...
- or even version 1 (latest) in comparison to version x

This mainly applies to cases which are manually created with different creation dates and version history - for automated testing across one full document, the default comparison on status as already implemented should be just fine.
