### ISSUE TITLE
SwtGui does not start with Java 10 

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#198]
1. URLClassloader is not included anymore ( see Utils#addJarToClasspath(File jarFile) ) which is used to load SWT at runtime.

Try solutions:
- determine OS and platform via start script and add Swt by `-cp` parameter when calling Java
   - [ ] Windows batch script
   - [ ] Windows Exe (see launch4j config in pom.xml)
   - [ ] MacOS command file
   - [ ] Linux shell script

2. JaxB throws Exceptions when (un-)marshalling XML/JSON  (TranskribusCore)
 - Unclear if only relevant when building Transkribus components with Java >= 9 or also at runtime. To be tested.

**Comment by jkloe** [comment]
Solution will be for now: the manifest of the main jar file contains an entry libs/swt-xx.jar where xx is the swt version. On each startup, we check if there is such a file in the libs directory, if not we copy the latest swt libs for that archticture to that location

**Comment by kahlep** [comment]
Linux bash script won't accept OpenJDK > version 10 to be a valid Java installation.

Steps to reproduce:
```
sudo apt install java11-runtime
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
cd $TRANSKRIBUS_HOME
./Transkribus.sh
```
`/usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar Transkribus-xxx.jar` works already.

**Comment by miha114** [comment]
The problem is the isValidJava function in the script. It fails because it tries to compare a version number which contains to periods - e.g. 11.0.3. Bash cannot do this. Solution is to add a function that enables comparison - taken from [here](https://stackoverflow.com/questions/16989598/bash-comparing-version-numbers) . 

I tested "the less flexible option": 

```
isValidJava() {
        
       echo "Checking java version of: "$1

	if [[ "$1" ]]; then
		function version { echo "$@" | gawk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }';}
		
		first_version=$("$1" -version 2>&1 | awk -F '"' '/version/ {print $2}')
		second_version="1.7"

		echo "Java version = "$first_version
	
		if [ "$(version "$first_version")" -le "$(version "$second_version")" ]; then
    		#	echo "false"
		        return 1;
		else
	    	#	echo "true"
		    	return 0;
		fi
	fi

	return 1;
}
```

With this the Transkribus.sh script runs even on 11-openjdk.

**Comment by kahlep** [comment]
Thanks @miha114! Works for me with version 1.8 as well as 11. I will update the bash script.
