### ISSUE TITLE
GUI is unable to reload page after a job has completed

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#199]
Page to load from the current document is determined by the method 
TrpDoc#getPageIndex(TrpPage page)

This method checks occurence using List#indexOf and the equals method of the object.
Depending of where this is called in the GUI, the pages to compare may have different lists of transcripts causing the method to return -1 errenously.

It's used in Storage#getPageIndex which fails each time the transcipt list changes.

**Comment by kahlep** [comment]
fix is a new implementation of TrpDoc#getPageIndex which is only used in GUI and affects:
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.applyAffineTransformToDoc()
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.nextPage()
eu.transkribus.swt_gui.mainwidget.PagesPagingToolBarListener.onEnterInPageFieldPressed()
eu.transkribus.swt_gui.mainwidget.storage.Storage.preloadSurroundingImages(String)
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.prevPage()
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentPage(boolean, boolean)
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentTranscript(boolean, boolean)
eu.transkribus.swt_gui.mainwidget.storage.Storage.reloadTranscriptsList(int)
eu.transkribus.swt_gui.mainwidget.storage.Storage.replacePageImgFile(File, IProgressMonitor)
eu.transkribus.swt_gui.mainwidget.DocJobUpdater.checkIfFinishedJobAffectsOpenedPage(...).() -> {...} Runnable.run()
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.reloadCurrentPage(...).new IRunnableWithProgress() {...}.run(IProgressMonitor)
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.unifiedExport().new IRunnableWithProgress() {...}.run(IProgressMonitor)
eu.transkribus.swt_gui.mainwidget.storage.Storage.saveTranscript(int, String)
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.saveTranscription(boolean)
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.showLocation(TrpLocation)
eu.transkribus.swt_gui.util.CurrentDocPagesSelector.updatePagesFromStorage()
eu.transkribus.swt_gui.mainwidget.TrpMainWidget.updateToolBars()
eu.transkribus.swt_gui.mainwidget.PagesPagingToolBarListener.updateToolBarValue()
eu.transkribus.swt_gui.util.DocPagesSelector.DocPagesSelector(...).new SelectionAdapter() {...}.widgetSelected(SelectionEvent)

**Comment by EvaMLang** [comment]
Maybe adding on to the problem from UI side: the job finished dialog triggers a reload of the current page (fine, if you are still on the page where the job was started)
side-effect: if you moved to a different page after starting the job, your currently opened page is also (unnecessarily) reloaded without properly triggering auto-save, so immediate changes are lost.

**Comment by hackmanschorsch** [comment]
In the 1.4.3.1_Snapshot the problem with reloading unnecessary pages is fixed. It needs a job update (for HTR and LA) so that the page string is set correctly in the TrpJobStatus. After that the check 'if current page is affected' should also work fine.
