### ISSUE TITLE
BaseLines merging - order of text wrong

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#203]
When two baselines (or the corresponding lines) are merged, the already existing reading order should be taken into account. 
Currently, the merge always produces "Text BText A" - whereas the concatenation should be "Text A Text B" , also adding an extra space between the two unicode lines.

**Comment by hackmanschorsch** [comment]
Fixed in CanvasSceneListener lines 763-769: now the merged shapes get sorted by their reading order instead of their coordinates. One extra space is added.
