### ISSUE TITLE
Orientation of image -  autorotate

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#208]
Current situation: If an image is uploaded with exif data e.g. w=4000 and h=3000 and orientation is 'rotate 90° counterclockwise' then the tools on the server take that version and the GUI auto-rotates it (because of the orientation tag). 

So currently we have a mismatch between server and GUI - this leads to the fact the image and the transcript resp. layout do not match in the canvas.
So either (1) store rotated image in the image store already during upload
or (2) do not autorotate in the GUI or if so you must also rotate the transcript data

**Comment by kahlep** [comment]
Erroneously reopened. This is dealt with in
https://github.com/Transkribus/TranskribusInterfaces/issues/5
https://github.com/Transkribus/TranskribusSwtGui/issues/154
