### ISSUE TITLE
Display last page when logging in toTranskribus

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#217]
Currently, upon login, the first page from the collection with the lowest colID is opened when the user logs in. 
Instead, Transkribus should display the last entry from the recent documents list for the user.

**Comment by kahlep** [comment]
This works since 409fe92c209edca7ed7ac757cc4441f2a3956ea3 but has to be enabled in `config.properties`:
`loadMostRecentDocOnLogin = true`

The UI for that could be done in #232
