### ISSUE TITLE
Load recent document after login and make behavior configurable

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#230]
Currently the first collection from the list is opened and the first document is loaded. On each collection change the first doc from the collection is loaded automatically.

1. [x] Unload any remote doc upon collection change rather than loading a random one
2. [x] Add option to config.properties
3. [x] Determine the most recently edited/viewed document, either by
   a. Getting the most recent user actions of type "Save" and "Access document" from the server. 
   b. Read this from the registry. This however lacks the server URL and encodes information into Strings 
4. [x] Load the most recently edited/viewed document automatically after login. 
5. [ ] Add ~~checkbox (?) to config dialog~~ config dialog for changing behavior

**Comment by kahlep** [comment]
3. started in 409fe92c209edca7ed7ac757cc4441f2a3956ea3

There is another event handler loading the first collection from the collection list. This triggers the handler from 1. and unloads the document again.
-> find this handler and put the code in one place

**Comment by kahlep** [comment]
Test Server actions API now allows to pass multiple action type IDs. Retrieval method picks the most recent action of type "Access Document", "Save" or "Status Change"

**Comment by kahlep** [comment]
4. fixed in 095fea7c48c545e94a03e236e000b3482c1cad73

**Comment by kahlep** [comment]
Works stable so far and can be enabled in `config.properties`:
`loadMostRecentDocOnLogin = true`

The UI for that could be done in #232

**Comment by hackmanschorsch** [comment]
feature enabled in the main menu (burger menu)
