### ISSUE TITLE
no more handles

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#25]
- on some windows systems "no more handles" errors occur although no memory leak has been detected
- may be caused by excessive use of handles by other applications (outlook, photoshop...) and thus handles are very limited for Transkribus
- possible solution: limit use of image handles in thumbs widget
- integrate Sleak (handle monitor) into DebuggerDialog to monitor active handles in running application

**Comment by hackmanschorsch** [comment]
The reason seems to be that on a 64 bit machine a 32 bit Java was installed! Also Java Hep space errors were observed and could be solved with updating.
