### ISSUE TITLE
ErrorRateTool: Tooltips in chart incorrect

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#255]
The tooltips on the individual chart entry are wrongly set and don't obey the natural page order.
Also, it probably would make sense to abbreviate "Page X" (x-axsis text) to simply "p. X" to cope with more than 10 entries.
![errorratedialog_tooltips_incorrect](https://user-images.githubusercontent.com/17451573/47783306-a43e0080-dd02-11e8-877d-114f11039350.PNG)

**Comment by EvaMLang** [comment]
one further comment here as well: The Error Rate Chart now only shows 10 entries (instead of 50 as in the example below)- I was hoping for one entry per page, maybe a line diagram could serve better for larger documents after all?
Thanks :-)
![image](https://user-images.githubusercontent.com/17451573/48079608-fa6fdf80-e1eb-11e8-91f7-2db2a237a29f.png)

**Comment by krf41037** [comment]
I cut down the number of pages in the chart to 10 with the intention to implement a button which allows to scroll the next results. A linechart was also in the discussion but was not used as the results are not connected by a line. Would you prefer scrolling or a linechart for many pages?

**Comment by EvaMLang** [comment]
We would in fact prefer a line chart representation for CER and WER, so the x-axis would be the pages, the y-axis would give you the entries of CER (line 1) and WER (line 2). The chart tool itself already allows zooming, so drilling down to further details is up to the user and quite handy already.  :-)
