### ISSUE TITLE
Incomplete display of page image on linux

### ISSUE THREAD

**Issue by JessedeDoes** [Transkribus/TranskribusSwtGui#265]
Transkribus 1.5.3 on mint 18.3

![image](https://user-images.githubusercontent.com/1109972/48697487-06dd3a80-ebe5-11e8-8ac1-1491c03f64bc.png)

BTW the display is fine on windows

**Comment by jkloe** [comment]
Thanks for reporting - the issue should be fixed with the new snapshot version 1.5.4.1-SNAPSHOT.
A new release is on its way.
