### ISSUE TITLE
Error Rate Tool - comparison fails when more than one HTR run is present

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#267]
Scenario:

1. Run HTR on document, calculate advanced accuracy statistics for complete document
2. Run (different) HTR on same document, calculate advance accuracy statistics for complete document

Result: statistics from second run are lost, only results of first run are available.

**Comment by krf41037** [comment]
Fixed with commit 1e9bedb7b7c57e4684da358436b445e56544961e
