### ISSUE TITLE
export of 'collection overview'

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#308]
export a descriptive list of all documents contained in a collection
format Excel or csv
values: docID, doc name, nr_of_pages, uploader?, nr_of_words, nr_of_chars?

**Comment by jkloe** [comment]
@hackmanschorsch maybe add additional fields if needed

**Comment by jkloe** [comment]
Problem with stats cols (nr-of-words, nr-of-transcribed-lines): currently, they have to be loaded for each collection individually. Maybe include loading of all stats for all docs again (maybe too slow?)?
