### ISSUE TITLE
TEI Export for Swiss Project

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TranskribusSwtGui#40]
Transkribus documents are used in the Swiss Project:  https://humarec.org 
They needsa more flexible TEI output for this project.
[TranskribustoEVT_update1-1.pdf](https://github.com/Transkribus/TranskribusSwtGui/files/831651/TranskribustoEVT_update1-1.pdf)

**Comment by funkyfuture** [comment]
it would be helpful if the `<lb>` element was configurable in the export dialog, e.g. the _Deutsches Textarchiv Basisformat_ [expects](http://www.deutschestextarchiv.de/doku/basisformat/lbAllg.html) them usually as empty elements after the line's content.

**Comment by hackmanschorsch** [comment]
From Transkribus version 1.4.3 everyone can/let create a project specific xslt. This is then choosable in the export dialog and transfroms the page XMLs into user/project specific TEI XMLs. The 'TEI base xslt' is here:
[https://github.com/dariok/page2tei](url)
