### ISSUE TITLE
Arabic writing

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TranskribusSwtGui#43]
User: allerdings funktioniert die Transkription mit arabischer Schrift noch nicht reibungslos (so ist das Eingabelayout, d.h. die Zeilenzahlen, orientiert an rechtsläufigen Schriften und die Satzzeichen werden nicht an der korrekten Stelle dargestellt). Kann man die Unterstützung für linksläufige Schriften irgendwo einstellen oder ist das noch nicht implementiert?

**Comment by jkloe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RTL issue on MAC](https://trello.com/c/BnLanJJ0/9-rtl-issue-on-mac)
