### ISSUE TITLE
Display name/email of last editor in Document Manager

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#52]
It would be great to quickly grasp who was the last editor (or is currently working) on each page within a document. This functionality could be part of the Document Manager and available as option (similar to "Show filename in label" functionality).

**Comment by hackmanschorsch** [comment]
Who is actually working can be found in the 'User activity' dialog. Who has saved each page is now shown in the document manager tree. (in next Snapshot or release)
