### ISSUE TITLE
Document Manager - select all pages at once

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#53]
- select all thumbnails at once by pushing Strg+A (useful for setting e.g. GT status for all pages in a document at once)

**Comment by hackmanschorsch** [comment]
Done (interesting bug - after selecting all thumbnails with Strg+A the pagestring of all selected pages contains the page 1 two times like 1,1,2,3,4,5...) Not clear why and how. May a bug in the nebula Gallery?? Not nice but works at the moment.

**Comment by hackmanschorsch** [comment]
Was replaced by a tree view. Use case of e.g. setting the status of all pages can be done by selecting the document and set the new status or select all pages in that document you want to change.
