### ISSUE TITLE
KeyEventListener: Canvas moving between regions

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#57]
During segmentation it would be really useful to easily move between text regions / table cells using the ALT+arrow (or similar) combinations. This worked in versions pre 1.0 and is not working any longer.

**Comment by jkloe** [comment]
Alt+arrow-left / arrow-right for jumping to the previous / next region in the transcription widget works for me.
Table cells can now also be iterated through with arrow keys when focus is in canvas, see commit 14254959cd31f1780a7a7c2c5f2dc0366d9f9463
