### ISSUE TITLE
Export: not working when doc title contains backslash

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#66]
If a document's title contains a backslash, the export dialog should escape this somehow. Now, it is interpreted as path component and export fails.

**Comment by jkloe** [comment]
Related to that issue: remove either eu.transkribus.core.model.builder.CommonExportPars or eu.transkribus.core.io.DocExporter.ExportOptions and merge its members!

**Comment by jkloe** [comment]
moved issue to TranskribusCore#6
