### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#7]
- Unified look & feel for all tagging (structural & text based)
  - Do not show all tags at the same time ("tag sets", locally defined per installation!?)
  - move most prominent text based tagging features to transcription toolbar (bold, cursive etc.)
  - shortcut system for tags

**Comment by jkloe** [comment]
Currently working on this issue, TODO's:
- [ ] integrate 'Comments' widget in new tag tab widget
- [ ] add some default tag specs when no "tagSpecs" property is found in the configuration file / on the server
- [ ] integrate tag search & replace btn into tag tab widget
- [ ] make tag tab widget undockable (really?)
- [ ] show only tag-specs in context menu
- [ ] store / load tag specs on / from server

**Comment by jkloe** [comment]
More issues with new tagging system:
- [ ] order of tags in tag list for current page should correspond to ordering of tags in the tag editor at the bottom

**Comment by EvaMLang** [comment]
Quick feedback:
The display of the tag-list looks great!

Bug found:
After tagging a new occurrence, the content of the transcription editor is set back to the first tagged entry in the tag list. The focus of the highlighted region in the canvas is correct! This probably relates to the very last unchecked issue above?

Additional wishes:
- [ ] Add a filter to the tag-list-widget to display ONLY one specific type, e.g. all abbrev tags.
- [ ] Allow updating properties without having to switch windows, for instance provide the expansion of an abbreviation immediately after tagging a word
