### ISSUE TITLE
Add representative image url to TrpCollection and TrpDoc

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#83]
Add the possibility to select a representative collection image and representative image for each document in the collection to be shown as a thumb image in the browsing interface on the web. Default image urls can be the first image (which could be empty) or the image from the middle? Store url directly to the TrpCollection and TrpDoc will give direct access to that thumbs.

**Comment by kahlep** [comment]
* Fix in TrpDocMetadata and TrpCollection beans: 
    * add pageID and image/thumb URL(s)
* Fix in TrpPersistence and DB: 
    * add foreign key on PAGES table pageID to DOC_MD and COLLECTION tables
    * join in respective data (filekey, URLs etc.) on all selects gathering doc and collection data
    * handle new data in resultset->bean mapping
