### ISSUE TITLE
PDF upload via FTP and for several PDFs at once

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#89]
Problem: PDF upload for bigger PDFs results in java heap space error.
And at the moment you have to repeat the procedure for each single PDF.

**Comment by EvaMLang** [comment]
Currently extraction of images is done on client side, then extracted images are zipped and zip file is uploaded - maybe this can be shifted to upload the pdf and do server-side extraction of images.

Question then: is there a limitation for file size in this case?

**Comment by EvaMLang** [comment]
Closing this issue as the file size for one pdf does not matter any longer. Was already fixed by commit in https://github.com/Transkribus/PdfUtils/commit/72dd536a6b363ad6e1d1cd832ec08a27086fcbe3
