### ISSUE TITLE
Selection of deleted document not triggered to GUI

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#93]
![2017-06-19_error_deletedoc](https://user-images.githubusercontent.com/17451573/27274156-81addce8-54d2-11e7-88bb-aa6e0409d29c.PNG)

Deleting an open document works fine, however, the deletion is not automatically triggered to the list of all documents in the current collection and the deleted document still remains open. Interestingly, the user can also change to other pages in the (deleted) document. The error message then differs, stating "Could not load page <no.>"
![2017-06-19_error_deletedoc_changepage](https://user-images.githubusercontent.com/17451573/27274385-506c2580-54d3-11e7-817a-b8ddfd6e157c.PNG)

In addition, the document can still be chosen from the list of documents - error message is not helping the normal user.

**Comment by hackmanschorsch** [comment]
Know with 'recycle bin' the problem is solved.
