### ISSUE TITLE
HTR Train/Test Set Viewer: Image is not redrawn on page change

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#96]
In the Viewer Dialog for Train/Test Sets of HTRs, the image is not redrawn automatically when the page is changed either via the next/previous page buttons or the thumbnails.
Only when the mouse pointer enters the image, it is redrawn with the current image.

**Comment by hackmanschorsch** [comment]
canvas.redraw() in loadImg method, DocImgViewerDialog, line 147
